### ISSUE TITLE
How to convert Seurat Object to Semla format?

### ISSUE THREAD

**Issue by ElyasMo** [ludvigla/semla#10]
Thanks for providing such a great toolkit.
Not sure if you have already implemented this function, but it would be great if you make converting a Seurat object to Semla format possible. It seems crucial and one should be able to switch between different formats and even programming languages as it is possible between Seurat and Scanpy.

**Comment by ludvigla** [comment]
I definitely agree with you that this would be a very useful feature. I think it should be feasible so I'll take a look at it.

**Comment by lfranzen** [comment]
Hello @ElyasMo, thank you for using semla! Ludvig has now implemented a new function called `UpdateSeuratForSemla()` that allows you to make an object created with Seurat compatible with semla. By updating your object using this function you should be able to use the Seurat spatial functionalities as well as all functions within semla. The function is available in the latest 1.1.0 release of semla.

Closing this issue as we have now hopefully adressed it by adding this new functionality.

Thank you for pointing this out and for your patience!
/Lovisa
