### ISSUE TITLE
How to adapt to spatial data not from V10

### ISSUE THREAD

**Issue by leiLQ** [ludvigla/semla#11]
Hi,

I'm analysing the spatial transcriptomics data from stereo-seq which doesn't have matching H&E image and has different raw data files from Visium. 

I have some issues in creating Staffli object with such data. I'm wondering does semla support spatial analysis without H&E image. If so, how could I skip the required image information in creating Staffli object?

Thanks so much!

**Comment by lfranzen** [comment]
Hello! Apologies for the late reply. Unfortunately semla does not support any other spatial platform than Visium at the moment, which is why it cannot process your stereo-seq data.
