### ISSUE TITLE
filtering normalization etc

### ISSUE THREAD

**Issue by chrkuo** [ludvigla/semla#12]
Hi I did not know that STUtility is now semla and have been trying to explore the tool but is there a preprocessing normalization scaling/filtering step?

**Comment by lfranzen** [comment]
Hello @chrkuo! You can apply any of the preprocessing functionalities provided through Seurat, such as normalization and scaling, in the same way as it could be achieved in STUtility. In our "Subset and merge" tutorial on the semla website you can moreover find help on how to use the `SubsetSTData()` function for filtering your data: https://ludvigla.github.io/semla/articles/subset_and_merge.html 

Hope that answers you questions!
/Lovisa

**Comment by lfranzen** [comment]
Closing the issue as no further response has been risen
