### ISSUE TITLE
load image error

### ISSUE THREAD

**Issue by chrkuo** [ludvigla/semla#13]
Hi 

I am encountering an error with loadimages:

> EWS4064 <- LoadImages(EWS4064)
Error in unique(object@meta.data[, "sample"]) : 
  no slot of name "meta.data" for this object of class "Staffli"

i followed the workflow on the setting up vignette to load the info table not sure how to circumvent this issue

**Comment by Lianfuwu** [comment]
> Hi
> 
> I am encountering an error with loadimages:
> 
> > EWS4064 <- LoadImages(EWS4064)
> > Error in unique([object@meta.data](mailto:object@meta.data)[, "sample"]) :
> > no slot of name "meta.data" for this object of class "Staffli"
> 
> i followed the workflow on the setting up vignette to load the info table not sure how to circumvent this issue

I encountered the same error. Please have you solved the error? I hope you can help me if you have an idea, thank you.

**Comment by ludvigla** [comment]
Is it possible that you have `STUtility` loaded in your R environment? 

The `Staffli` object in `semla` doesn't have a slot called `meta.data`, but it did in `STUtility`. If you have `STUtility` loaded, you are probably using the wrong `LoadImages` function.

**Comment by Lianfuwu** [comment]
> Is it possible that you have `STUtility` loaded in your R environment?
> 
> The `Staffli` object in `semla` doesn't have a slot called `meta.data`, but it did in `STUtility`. If you have `STUtility` loaded, you are probably using the wrong `LoadImages` function.

Hello,
I didn't install STUtility， Do I  need to create a meta.data slot in Staffli object? How can I do this? Thank you.
