### ISSUE TITLE
neighborhood mapping error

### ISSUE THREAD

**Issue by chrkuo** [ludvigla/semla#14]
Hi, 

@ludvigla I transitioned to semla after hitting a wall with proceeding with neighborhood analysis in STUTility but the same error is popping up when I am trying to map neighborhoods. It consistently keeps saying the rows don't match although I see my meta-data with a lot of NAs and those that were annotated to be neighbors. I have posted this issue with dplyr and they think its something wrong inherently with the package of semla and not dplyr. Can I please get some assistance.

Thank you

**Comment by ludvigla** [comment]
Hi,

I'll try to help you out but I will need more information to go on. If you have NA values in the meta data that could be the issue. 

Would you be able to share the object? That would make it easier for me to figure out what's wrong. 

/Ludvig

**Comment by chrkuo** [comment]
@ludvigla absolutely what is your email. I will send it right now 

> Hi,
> 
> I'll try to help you out but I will need more information to go on. If you have NA values in the meta data that could be the issue.
> 
> Would you be able to share the object? That would make it easier for me to figure out what's wrong.
> 
> /Ludvig



> Hi,
> 
> I'll try to help you out but I will need more information to go on. If you have NA values in the meta data that could be the issue.
> 
> Would you be able to share the object? That would make it easier for me to figure out what's wrong.
> 
> /Ludvig

Absolutely what is your email and I will send it right now. 

I thought the region-neighbor code is supposed to generate NA for any spots that are not neighbors. I had a bunch of NAs along with few nbs_X

**Comment by chrkuo** [comment]
@ludvigla any updates. is the regionneighbour code supposed to generate NA values?

**Comment by ludvigla** [comment]
Here's my email: ludvig.larsson@scilifelab.se.

I think I will need to take a closer look on the data in order to figure out what's going on. Could you aslo share the code that you ran?

/Ludvig

**Comment by chrkuo** [comment]
@ludvigla any updates. 

Thank you so much
