### ISSUE TITLE
Error installing semla because of the get_array_rotation.R

### ISSUE THREAD

**Issue by LisaWang2022** [ludvigla/semla#17]
The error description:

* installing to library ‘/usr/local/lib/R/site-library’
* installing *source* package ‘semla’ ...
** using staged installation
** R
Error in .install_package_code_files(".", instdir) :
files in '/tmp/RtmpbhTpmE/R.INSTALL4a1d3ac097e5/semla/R' missing from 'Collate' field:
  get_array_rotation.R
ERROR: unable to collate and parse R files for package ‘semla’
* removing ‘/usr/local/lib/R/site-library/semla’
*
Maybe there are some files missing while construcint the R package?

**Comment by ludvigla** [comment]
I think the issue should be fixed now if you re-install the package.

Cheers,
Ludvig
