### ISSUE TITLE
Package download issue

### ISSUE THREAD

**Issue by YangXuuu** [ludvigla/semla#2]
Hi

I just had a package downloading issue, when try to download using "remotes::install_github("ludvigla/semla")"

The error message turns out to be "Downloading GitHub repo ludvigla/semla@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/ludvigla/semla/tarball/HEAD' failed"

I think my internet is all fine and the this web is accessible to public, so a bit confused

**Comment by ludvigla** [comment]
Hi!

I just tested it in a new environment and it worked fine :-/ What platform are you running on? Maybe you can try to install it via `devtools`:

````
devtools::install_github("ludvigla/semla")
````

/Ludvig

**Comment by YangXuuu** [comment]
Thanks, now it works!

**Comment by cjhong** [comment]
As of 9/4/23, I have exactly the same error as YangXuuu encountered.

**Comment by ludvigla** [comment]
Hi there,

The installation probably fails because of a download timeout. You can try to set the timeout in R:

`options(timeout=1000)`

and then run:

`remotes::install_github("ludvigla/semla")`

If it still fails, try increasing the timeout.

/Ludvig

**Comment by cjhong** [comment]
Thank you so much! It works now.
