### ISSUE TITLE
is there the ability to look at neighbors two spots away?

### ISSUE THREAD

**Issue by whitneyt1** [ludvigla/semla#30]
Hello,

I was looking through some of the code and am wondering if there is the ability to look at neighbors within a two spot radius? Will changing nNeighbors in `GetSpatialNetwork(object, nNeighbors = 6, maxDist = NULL, minK = 0, ...) increase the radius or still just look for directly adjacent spots?

Thanks!
Whitney
`

**Comment by ludvigla** [comment]
Hi Whitney!

You have several options. You can increase the nNeighbors to increase the local neighborhood, but then you also need to increase maxDist. For example, if you set nNeighbors = 12 and maxDist = Inf, you should get the 12 closest neighbors. But if you want to know get neighbors that are two steps away in the hexagonal grid, you need to figure out what the appropriate maxDist for those neighbors is and set nNeighbors to some high value to make sure that all those spots are included.

At the top of my head I don't know exactly what this maxDist number is, but I guess it should be roughly two spot center-to-center distances. It's pretty easy to get the center-to-center distances from the spatial coordinates table! 

/Ludvig

**Comment by whitneyt1** [comment]
Thank you!!!!
