### ISSUE TITLE
How to get the transformed images by semla into the original Seurat object?

### ISSUE THREAD

**Issue by vagm110901** [ludvigla/semla#31]
Hello,
I want to recover the transformed images done by semla which are saved in `semlaObject@tools$Staffli@rasterlists$transformed` in order to use them with Seurat functions. I have tried with `UpdateSeuratFromSemla()` function, but the images saved in `seuratObject@images` after doing it are the original ones (the raw images) instead of the transformed ones. 
How could I recover the transformed images to use them with Seurat functions?
Thanks!

**Comment by jemorlanes** [comment]
Hello and thanks for using the package!! :)

We have updated the `UpdateSeuratFromSemla()` function. Now there is a new argument allowing the user to decide if they want to load the `transformed` or the `raw` image for the Seurat object. The website is not yet updated with this information, but find an example on how to use this new version here:

```
# Load example Visium data
 se_mbrain <- readRDS(system.file("extdata/mousebrain", "se_mbrain", package = "semla"))
 se_mcolon <- readRDS(system.file("extdata/mousecolon", "se_mcolon", package = "semla"))
 se_merged <- MergeSTData(se_mbrain, se_mcolon)
 
# Update object
 se_merged <- UpdateSeuratFromSemla(se_merged)
 
# Use Seurat functions
 SpatialFeaturePlot(se_merged, features = "Nrgn")
 
 # Transform images in object
 se_merged <- LoadImages(se_merged)
 rotation_angle <- get_array_rotation(se, grid_pattern = "hexagonal")
 transforms <- rbind(generate_rigid_transform(sampleID = 1L, angle = rotation_angle$`1`),
                     generate_rigid_transform(sampleID = 2L, angle = 12))
 se_merged <- RigidTransformImages(se_merged, transforms = transforms)
 
 # Update object
 se_raw <- UpdateSeuratFromSemla(se_merged, image_use = "transformed")
 se_transformed <- UpdateSeuratFromSemla(se_merged, image_use = "raw")
 
 # Use Seurat functions
 p1 <- SpatialFeaturePlot(se_raw, features = "Nrgn")
 p2 <- SpatialFeaturePlot(se_transformed, features = "Nrgn")
 p1 | p2
```

This issue originates from Seurat's limitation of not allowing for more than 1 image to be loaded for their spatial plotting functions. Unless you really want to use some specific Seurat functions, we recommend sticking to semla's. Nevertheless, now you can choose to load semla's transformed image for Seurat plotting! :))

**Comment by lfranzen** [comment]
This issue has now been solved in semla v.1.2.0 by adding the additional argument `image_use` to the `UpdateSeuratFromSemla()` function where the user can specify whether the "raw" or "transformed" image should be kept.

See release notes [here](https://ludvigla.github.io/semla/news/index.html) and function documentation [here](https://ludvigla.github.io/semla/reference/UpdateSeuratFromSemla.html?q=UpdateSeuratFromSemla#ref-usage).
