### ISSUE TITLE
Feature request - barcode level metadata during loading

### ISSUE THREAD

**Issue by williamsdrake** [ludvigla/semla#5]
Hi,

Really like the package so far. I'm currently analyzing 10X visium data. It would be nice if there was an option to specify a two column CSV file that contains a list of spot barcodes in Col1 and the corresponding pathology annotation to which it belongs in Col2 (the output of [the steps outlined here](https://kb.10xgenomics.com/hc/en-us/articles/360058943912-How-can-I-transfer-pathologist-annotations-to-Loupe-Browser-)). The csv location could be included in the infoTable, since each sample would have its own csv file. Currently only sample level metadata is supported in the ReadVisiumData function.

**Comment by ludvigla** [comment]
Hi,

I have included a new feature that can be used to load annotations with `ReadVisiumData`. You will need to install the dev version of semla to use this feature. An example is provided in the function reference, but I'll include it here too:

````
samples <-
  Sys.glob(paths = paste0(system.file("extdata", package = "semla"),
                          "/*/filtered_feature_bc_matrix.h5"))
imgs <-
  Sys.glob(paths = paste0(system.file("extdata", package = "semla"),
                          "/*/spatial/tissue_lowres_image.jpg"))
spotfiles <-
  Sys.glob(paths = paste0(system.file("extdata", package = "semla"),
                          "/*/spatial/tissue_positions_list.csv"))
json <-
  Sys.glob(paths = paste0(system.file("extdata", package = "semla"),
                          "/*/spatial/scalefactors_json.json"))
annotation_file <- 
  Sys.glob(paths = paste0(system.file("extdata", package = "semla"),
                          "/*/galt_spots.csv"))
annotation_files <- c(NA_character_, annotation_file)

# Create a tibble/data.frame with file paths
library(tibble)
infoTable <- tibble(samples, imgs, spotfiles, json, sample_id = c("mousebrain", "mousecolon"), annotation_files)

se <- ReadVisiumData(infoTable)
````

Let me know what you think.

/Ludvig

**Comment by williamsdrake** [comment]
I also found a function on stackoverflow to check for multibyte characters, but doesn't seem to find any in my table

```
find_offending_character <- function(x, maxStringLength=256){  
  for (c in 1:maxStringLength){
    offendingChar <- substr(x,c,c)
    #the next character is the offending multibyte Character
  }    
}


lapply(infoTable, find_offending_character)

```
```
$samples
NULL

$imgs
NULL

$spotfiles
NULL

$json
NULL

$orig.ident
NULL

$section
NULL

$status
NULL

$run
NULL

$annotation_file
NULL
```
