### ISSUE TITLE
Error in `geom_point()`: ! Problem while converting geom to grob. ℹ Error occurred in the 1st layer.

### ISSUE THREAD

**Issue by whitneyt1** [ludvigla/semla#6]
Hello,

When trying to map multiple features, I receive this error:
<img width="816" alt="Screen Shot 2023-04-26 at 6 00 27 PM" src="https://user-images.githubusercontent.com/46573884/234733320-b29b1a7e-7aba-4959-89ef-e1a2db480de4.png">

I have tried with ggplot2 version 3.4.2 and 3.4.0. 

Thank you!

**Comment by whitneyt1** [comment]
<img width="472" alt="Screen Shot 2023-04-26 at 6 03 55 PM" src="https://user-images.githubusercontent.com/46573884/234733711-a067fe42-4d55-44d9-93de-1a55d1233d6b.png">

**Comment by whitneyt1** [comment]
sorry. I have resolved this by specifying `section_number=1`

**Comment by ludvigla** [comment]
Thank your for reporting this. Seems like a bug that occurs when some spots have NA values. The bug should be fixed now!

Cheers,
Ludvig
