### ISSUE TITLE
Error with LoadImages and MapFeaturesSummary

### ISSUE THREAD

**Issue by AlinaO90** [ludvigla/semla#7]
Hi, 

I am following one of the tutorials on the Semla website and I am having trouble using the image features from the package. 

When I run LoadImages I get the following error:

<img width="665" alt="image" src="https://user-images.githubusercontent.com/18200044/236240098-0baebd69-d112-492d-b00f-447d8f211413.png">

In the img column of the infoTable tibble, I do have 'detected_tissue_image.jpg' but I have tried even with the tissue_lowres_image.png and I get the same error.

Additionally, when I try to use MapFeatureSummary I get this error:
<img width="784" alt="image" src="https://user-images.githubusercontent.com/18200044/236240945-967c8a3a-ac24-435f-9c11-4e2049531ec4.png">

I am using cytassist images, I am using R 4.1.1 and here is my sessionInfo()

<img width="971" alt="image" src="https://user-images.githubusercontent.com/18200044/236242112-c9cd94fe-c609-435d-8e1e-1191ee01458d.png">

Do you know what could be going wrong here? Thanks

**Comment by lfranzen** [comment]
Hi! First of all, apologies for the very late response, we have seen you issue but are not really able to recreate it and have therefore not been able to adress it.
Did you manage to find a solution to it in the end or does it still give you errors?

**Comment by lfranzen** [comment]
Stale thread – closing issue
